export const PAYMENT_AMOUNTS = {
  MINT_ONE_PAYMENT_AMOUNT: process.env.REACT_APP_MINT_ONE_PAYMENT_AMOUNT || '2000000000',
  MINT_COPIES_PAYMENT_AMOUNT: process.env.REACT_APP_MINT_COPIES_PAYMENT_AMOUNT || '100000000000',
  BURN_ONE_PAYMENT_AMOUNT: process.env.REACT_APP_BURN_ONE_PAYMENT_AMOUNT || '12000000000',
  MINT_ONE_META_SIZE: process.env.REACT_APP_MINT_ONE_META_SIZE || '1',
  MINT_COPIES_META_SIZE: process.env.REACT_APP_MINT_COPIES_META_SIZE || '10',
  MINT_MANY_META_SIZE: process.env.REACT_APP_MINT_MANY_META_SIZE || '5',
  MINT_MANY_META_COUNT: process.env.REACT_APP_MINT_MANY_META_COUNT || '5',
  MINT_COPIES_COUNT: process.env.REACT_APP_MINT_COPIES_COUNT || '20',
}